### ISSUE TITLE
Make this project active again!

### ISSUE THREAD

**Issue by niansa** [satoshinm/WebSandboxMC#100]
This project had no development since a long time. Please continue it! :D

**Comment by satoshinm** [comment]
@niansa I hear you, would like this project to be continued as well unfortunately there is a severe lack of development resources. But I have just added it to https://www.codeshelter.co so someone could be able to pick it up where I left off, hopefully! Looking for dedicated developers, if you know any...

**Comment by niansa** [comment]
Great. We'll see!

**Comment by satoshinm** [comment]
@niansa Released a v1.10.5 update at https://www.spigotmc.org/resources/websandboxmc.39415/
