### ISSUE TITLE
Web spawn default to server spawn, World#getSpawnLocation()

### ISSUE THREAD

**Issue by satoshinm** [satoshinm/WebSandboxMC#70]
If no web center x/y/z radius location is set, or as an option, could instead use the server's spawn location. There is a Bukkit API to get this location, World#getSpawnLocation: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/World.html#getSpawnLocation--, probably easy to add.

Requested in private message https://www.spigotmc.org/conversations/please-help-me-with-websandboxmc.211573/page-2#message-1263964

---

    + * If x/y/z center are all 0, then the world's spawn location is used instead

**Comment by chillerkraft** [comment]
epic! TESTING SOON! might finally be able to implement on my server!

**Comment by chillerkraft** [comment]
i'd love to be able to let web players build somewhere though.. ;)

**Comment by chillerkraft** [comment]
imagine if plugin Residence (free version available on premium page description) could allow players to let certain web players be able to build in certain residence areas or subzones..
orr if i could specify in config an area where web players can build...
orr if i could let web players choose areas to build in and let them log in later to regain access

ideas ideas ideas

**Comment by satoshinm** [comment]
@chillerkraft Good idea, basically allowing players to check in on their own home from out of the game, I opened an issue for Residence integration: https://github.com/satoshinm/WebSandboxMC/issues/75 - it could work well with multiple web client sandboxes https://github.com/satoshinm/WebSandboxMC/issues/71, shouldn't be too difficult with the current design but would require some kind of authentication system: https://github.com/satoshinm/WebSandboxMC/issues/48 (since currently everyone is a "web guest")
