### ISSUE TITLE
WebSandbowMC blocks

### ISSUE THREAD

**Issue by SeussCZ** [satoshinm/WebSandboxMC#94]
Hello, why i dont see block on spawn? I see players only. Thanks

https://ctrlv.cz/shots/2017/06/15/ehgs.png

**Comment by satoshinm** [comment]
@SeussCZ it could be your web sandbox center is too high, so those are the only blocks within the radius. Try editing plugins/WebSandboxMC/config.yml and change `y_center` (and/or `x_center` and `z_center`, if needed), to move the location of the web sandbox. If that doesn't fix it could you send me: 1. version of the plugin 2. version of the server platform (/version), 3. contents of plugins/WebSandboxMC and 4. relevant part of your worlds/world/*.mca file and I'll see if I can replicate the problem myself to investigate

**Comment by satoshinm** [comment]
@SeussCZ can you provide the requested information?
